"""Comments foreign keys, redone 3rd

Revision ID: 21082fc3bf2b
Revises: cfe96bc30914
Create Date: 2020-02-10 19:17:58.131248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21082fc3bf2b'
down_revision = 'cfe96bc30914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_ibfk_1', 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
