"""add language to posts

Revision ID: 225a6001e867
Revises: 939c0bb9d36e
Create Date: 2019-08-23 22:08:25.999561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225a6001e867'
down_revision = '939c0bb9d36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
